GB-609: create/update `.git/gitbutler.json`
gitbutlerapp/gitbutler pull request #1328
Opened 2023-10-10 11:34 UTC by extrawurst

this happens when a new session is created

2023-10-10 11:43 UTC, ngalaiko requested changes
you have to use a different path, and also maybe add a simple test? we have those in the `gb_repository/repository_tests.rs`

2023-10-10 11:43 UTC, ngalaiko commented on packages/tauri/src/gb_repository/repository.rs
> +        tracing::info!("gitbutler file updated: {:?}", gb_file_path);
let's make it debug, @mtsgrd doesn't like noisy logs 🙂

2023-10-10 11:43 UTC, ngalaiko commented on packages/tauri/src/project_repository/repository.rs
> +    }
i think what @schacon meant by gb_path is the path of the `gb_repository.git_repository`

anyhow, `gb_` is usually related to our data repository, and here you have a path to the user's project repository that is not gb.

2023-10-10 12:01 UTC, schacon commented on packages/tauri/src/project_repository/repository.rs
> +    }
Yes, I wanted the path to the gitbutler git repository, not the project git repository. 👍

2023-10-11 06:41 UTC, ngalaiko approved these changes

2023-10-11 07:51 UTC, merged