Help window menu added
gitbutlerapp/gitbutler pull request #3693
Opened 2024-05-05 19:41 UTC by PavelLaptev

2024-05-05 20:49 UTC, PavelLaptev commented
@Qix- I'm wondering if we can add the app version there. It could solve this issue https://github.com/gitbutlerapp/gitbutler/issues/3590

if I do this:
```rs
  help_menu = help_menu.add_item(disabled_menu_item(
        "help/version",
        format!("Version {}", _package_info.version).as_str(),
    ));
```

I see this:
![image](https://github.com/gitbutlerapp/gitbutler/assets/18498712/184f2929-b5a0-44d2-957f-8bddd104c0a4)

Is this correct way to display the app version

2024-05-06 09:01 UTC, Qix- commented
That might actually work, but you might need to run the tauri bundling step instead of just local dev.

2024-05-06 10:06 UTC, Qix- commented on crates/gitbutler-tauri/src/menu.rs
> +
Can you remove this comment?

2024-05-06 10:06 UTC, Qix- commented on crates/gitbutler-tauri/src/menu.rs
> +// Command to set menu item enabled or disabled
This one too?

2024-05-06 10:06 UTC, Qix- commented on crates/gitbutler-tauri/src/menu.rs
> +    // Retrieve the main window from the app handle
And this one? They aren't adding a whole lot.

2024-05-06 10:09 UTC, Qix- requested changes

2024-05-06 10:09 UTC, Qix- commented on crates/gitbutler-tauri/src/menu.rs
> +        format!("Version {}", _package_info.version).as_str(),
```suggestion
        &format!("Version {}", _package_info.version),
```
This should work.

2024-05-06 10:14 UTC, Qix- commented on crates/gitbutler-tauri/src/menu.rs
> +    if event.menu_item_id() == "help/documentation" {
These `if` statements can be a single match statement.

```rust
let result = match event.menu_item_id() {
    "help/documentation" => open::that("..."),
    "something/else" => open::that("..."),
    unknown => panic!("unknown event emitted"),
};

if let Err(err) = result {
    tracing::error!(error = ?err, "failed to open url for {}", event.menu_item_id());
}
```

Something like that.

2024-05-06 10:27 UTC, Qix- approved these changes

2024-05-06 10:37 UTC, merged